//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   Een sterk getypeerde bronklasse waarmee u kunt zoeken naar gelokaliseerde tekenreeksen, enz.
    /// </summary>
    // Deze klasse wordt automatisch gegenereerd met de StronglyTypedResourceBuilder
    // klasse via een hulpprogramma zoals ResGen of Visual Studio.
    // Als u een lid wilt toevoegen of verwijderen, bewerkt u het .ResX-bestand en voert u ResGen opnieuw uit
    // met de optie /str, of u bouwt het VS-project opnieuw.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourneert het exemplaar van ResourceManager dat in het cachegeheugen is opgeslagen en dat wordt gebruikt in deze klasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScoreBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overschrijft de huidige CurrentUICulture-eigenschap voor alle
        ///   bronzoekacties waarvoor deze sterk getypeerde bronklasse wordt gebruikt.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
